id: 10002
name: Google Analytics Alternative
items:
  - matomo-org/matomo
  - plausible/analytics
  - Open-Web-Analytics/Open-Web-Analytics
  - snowplow/snowplow
  - umami-software/umami
  - allinurl/goaccess
  - electerious/Ackee
  - Countly/countly-server
  - PostHog/posthog
  - rudderlabs/rudder-server