id: 10001
name: CSS Framework
items:
  - twbs/bootstrap
  - foundation/foundation-sites
  - jgthms/bulma
  - uikit/uikit
  - Semantic-Org/Semantic-UI
  - Dogfalo/materialize
  - pure-css/pure
  - tailwindlabs/tailwindcss