id: 10025
name: Distributed File Storage
items:
  - ceph/ceph
  - gluster/glusterfs
  - s3fs-fuse/s3fs-fuse
  - juicedata/juicefs
  - kahing/goofys
  - littlefs-project/littlefs
  - sjqzhang/go-fastdfs
  - cubefs/cubefs
  - moosefs/moosefs
  - Alluxio/alluxio
  - minio/minio
  - storj/storj
  - seaweedfs/seaweedfs
  - opencurve/curve
  - apache/hadoop
  - apache/ozone
