id: 10032
name: Message and Streaming
items:
  - apache/pulsar
  - apache/kafka
  - rabbitmq/rabbitmq-server
  - apache/activemq
  - apache/rocketmq
  - nsqio/nsq
  - celery/celery
  - redpanda-data/redpanda
  - nats-io/nats-server
  - distribworks/dkron
  - emqx/emqx
  - zeromq/libzmq
  - vernemq/vernemq
  - apache/flink
  - bloomberg/blazingmq
  - AutoMQ/automq
  
