id: 10030
name: Finance
items:
  - OpenBB-finance/OpenBB
  - vnpy/vnpy
  - waditu/tushare
  - microsoft/qlib
  - ranaroussi/yfinance
  - TA-Lib/ta-lib-python
  - QuantConnect/Lean
  - akfamily/akshare
  - StockSharp/StockSharp
  - ricequant/rqalpha
  - robertmartin8/PyPortfolioOpt
  - twopirllc/pandas-ta
  - quantopian/alphalens
  - ranaroussi/quantstats
