id: 10096
name: Project Management
items:
  - AppFlowy-IO/AppFlowy
  - makeplane/plane
  - mattermost-community/focalboard
  - frappe/erpnext
  - hcengineering/platform
  - opf/openproject
  - kanboard/kanboard
  - kuaifan/dootask
  - Leantime/leantime
  - JordanKnott/taskcafe
