id: 2
name: Open Source Database
items:
  - qdrant/qdrant
  - elastic/elasticsearch
  - pingcap/tidb
  - cockroachdb/cockroach
  - ClickHouse/ClickHouse
  - mongodb/mongo
  - vitessio/vitess
  - apache/druid
  - tikv/tikv
  - apple/foundationdb
  - yugabyte/yugabyte-db
  - citusdata/citus
  - greenplum-db/gpdb
  - trinodb/trino
  - apache/hbase
  - MariaDB/server
  - apache/hive
  - apache/ignite
  - apache/doris
  - apache/kylin
  - StarRocks/starrocks
  - percona/percona-server
  - oceanbase/oceanbase
  - databendlabs/databend
  - taosdata/TDengine
  - risinglightdb/risinglight
  - polardb/polardbx-sql
  - polardb/polardbx-engine
  - risingwavelabs/risingwave
  - prestodb/presto
  - FerretDB/FerretDB
  - apache/horaedb
  - postgres/postgres
  - duckdb/duckdb
  - apache/shardingsphere
  - milvus-io/milvus
  - CUBRID/cubrid
  - GreptimeTeam/greptimedb
  - apache/cloudberry
